# Generated by Django 4.2.26 on 2025-11-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('venue', models.CharField(blank=True, max_length=140)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True, max_length=280)),
                ('visibility', models.CharField(choices=[('public', 'public'), ('removed', 'removed')], db_index=True, default='public', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user', models.CharField(db_index=True, max_length=50)),
                ('body', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploaded_posts/')),
                ('visibility', models.CharField(choices=[('public', 'public'), ('removed', 'removed')], db_index=True, default='public', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
