# Generated by Django 4.2.26 on 2025-11-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
