# Generated by Django 4.2.23 on 2025-10-08 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("artist_display_name", models.CharField(max_length=200)),
                ("owner_user", models.CharField(db_index=True, max_length=100)),
                (
                    "audio_file",
                    models.FileField(
                        upload_to="uploaded_songs/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav", "ogg", "m4a", "flac"]
                            )
                        ],
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="uploaded_covers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "public"), ("removed", "removed")],
                        db_index=True,
                        default="public",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "db_table": "Songs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Users",
            },
        ),
    ]
