# Generated by Django 4.2.23 on 2025-10-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio_sesion", "0003_users_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_superadmin",
            field=models.BooleanField(default=False),
        ),
    ]
