# Generated by Django 4.2.23 on 2025-10-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio_sesion", "0004_users_is_superadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="audio_sha256",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["owner_user", "audio_sha256", "visibility"],
                name="idx_song_owner_hash_vis",
            ),
        ),
    ]
