# Generated by Django 4.2.23 on 2025-10-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inicio_sesion", "0005_song_audio_sha256_song_idx_song_owner_hash_vis"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="genre",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
    ]
