# Generated by Django 4.2.23 on 2025-11-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0006_song_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idUser', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('portada', models.URLField()),
                ('isprivate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_songs', to='inicio_sesion.playlist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio_sesion.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('playlist_id', 'song_id')},
            },
        ),
    ]
