# Generated by Django 4.2.23 on 2025-11-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0007_playlist_playlistsong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlistsong',
            options={},
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='playlist_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='song_id',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='playlistsong',
            table='PlayListSong',
        ),
    ]
