# Generated by Django 4.2.23 on 2025-11-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0008_alter_playlist_options_alter_playlistsong_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='PlayList',
        ),
    ]
