# Generated by Django 4.2.23 on 2025-11-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0009_alter_playlist_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
