# Generated by Django 4.2.23 on 2025-11-10 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0010_alter_playlistsong_options_alter_playlistsong_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'managed': False},
        ),
    ]
