# Generated by Django 5.2.8 on 2025-11-11 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inicio_sesion', '0011_alter_playlistsong_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlistsong',
            table='PlayListSongs',
        ),
        migrations.CreateModel(
            name='LikeMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='inicio_sesion.users')),
            ],
            options={
                'db_table': 'LikeMedia',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='idx_likemedia_ct_obj')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
