# Generated by Django 4.2.26 on 2025-11-11 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0011_alter_playlistsong_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlistsong',
            table='PlayListSongs',
        ),
    ]
