# Generated by Django 4.2.26 on 2025-11-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0012_alter_playlistsong_table'),
        ('inicio_sesion', '0012_alter_playlistsong_table_likemedia'),
    ]

    operations = [
    ]
