# Generated by Django 5.2.8 on 2025-11-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0012_alter_playlistsong_table'),
        ('inicio_sesion', '0012_alter_playlistsong_table_likemedia'),
    ]

    operations = [
    ]
