# Generated by Django 4.2.26 on 2025-11-12 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0013_merge_20251111_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('venue', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('tickets_url', models.URLField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ArtistEvents',
                'ordering': ['start_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WallPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='inicio_sesion.artistprofile')),
            ],
            options={
                'db_table': 'WallPosts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist', 'created_at'], name='idx_post_artist_created')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('concert', 'Concierto'), ('showcase', 'Presentación / Showcase'), ('charity', 'Caridad / Beneficencia'), ('collab', 'Colaboración / Invitado'), ('meet', 'Meet & Greet / Firmas'), ('fanclub', 'Club de fans'), ('workshop', 'Taller / Masterclass'), ('livestream', 'Live / Streaming'), ('private', 'Evento privado'), ('other', 'Otro')], db_index=True, default='concert', max_length=32)),
                ('category_other', models.CharField(blank=True, max_length=80)),
                ('visibility', models.CharField(choices=[('public', 'Público'), ('unlisted', 'No listado'), ('private', 'Privado')], db_index=True, default='public', max_length=16)),
                ('host_role', models.CharField(choices=[('host', 'Anfitrión'), ('cohost', 'Co-anfitrión'), ('guest', 'Invitado')], default='host', max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=64)),
                ('location_type', models.CharField(choices=[('onsite', 'Presencial'), ('online', 'En línea'), ('hybrid', 'Híbrido')], default='onsite', max_length=8)),
                ('venue_name', models.CharField(blank=True, max_length=160)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('online_url', models.URLField(blank=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='MXN', max_length=8)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('tickets_url', models.URLField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event_covers/')),
                ('status', models.CharField(default='published', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inicio_sesion.artistprofile')),
            ],
            options={
                'db_table': 'Events',
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['organizer', 'start_at'], name='idx_event_org_start'), models.Index(fields=['category'], name='idx_event_category'), models.Index(fields=['visibility'], name='idx_event_visibility')],
            },
        ),
    ]
