# Generated by Django 4.2.26 on 2025-11-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0014_artistevent_wallpost_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='wallpost',
            name='artist',
        ),
        migrations.DeleteModel(
            name='ArtistEvent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='WallPost',
        ),
    ]
