# Generated by Django 4.2.26 on 2025-11-14 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0013_merge_20251113_1349'),
        ('inicio_sesion', '0015_remove_event_organizer_remove_wallpost_artist_and_more'),
    ]

    operations = [
    ]
