# Generated by Django 4.2.26 on 2025-11-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0016_merge_20251113_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'managed': True},
        ),
    ]
