# Generated by Django 4.2.26 on 2025-11-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0017_alter_playlist_options_alter_playlistsong_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='portada',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlistsong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
