# Generated by Django 4.2.26 on 2025-11-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0018_alter_playlistsong_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlistsong',
            options={'managed': False},
        ),
    ]
