# Generated by Django 4.2.26 on 2025-11-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0019_alter_playlist_options_alter_playlistsong_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='playlist',
            table='inicio_sesion_playlist',
        ),
        migrations.AlterModelTable(
            name='playlistsong',
            table='PlayListSong',
        ),
    ]
