# Generated by Django 5.2.8 on 2025-11-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0020_alter_playlist_table_alter_playlistsong_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.IntegerField(db_index=True)),
                ('collaborator_user', models.CharField(db_index=True, max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PlaylistCollaborators',
                'ordering': ['-added_at'],
                'unique_together': {('playlist_id', 'collaborator_user')},
            },
        ),
    ]
