# Generated by Django 4.2.26 on 2025-11-24 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0021_playlistcollaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_followers', to='inicio_sesion.users')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_artists', to='inicio_sesion.users')),
            ],
            options={
                'db_table': 'FollowArtists',
                'indexes': [models.Index(fields=['artist'], name='idx_follow_artist_artist'), models.Index(fields=['follower'], name='idx_follow_artist_follower')],
                'unique_together': {('follower', 'artist')},
            },
        ),
    ]
