# Generated by Django 4.2.26 on 2025-11-25 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio_sesion', '0022_followartist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Followers',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='playlistcollaborator',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='playlistcollaborator',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='playlistcollaborator',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playlistcollaborator',
            name='role',
            field=models.CharField(choices=[('editor', 'editor'), ('viewer', 'viewer')], default='editor', max_length=16),
        ),
        migrations.AddField(
            model_name='playlistcollaborator',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist_collaborations', to='inicio_sesion.users'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistcollaborator',
            unique_together={('playlist_id', 'user')},
        ),
        migrations.AddIndex(
            model_name='playlistcollaborator',
            index=models.Index(fields=['playlist_id'], name='idx_plcollab_playlist'),
        ),
        migrations.RemoveField(
            model_name='playlistcollaborator',
            name='collaborator_user',
        ),
    ]
